@urlDev=http://localhost:9000

### V1##########################################################


### CATEGORIES#######

###### get all
# GET {{urlDev}}/v1/categories
GET http://localhost:9000/v1/categories

###Update the image of one category
POST http://localhost:9000/v1/categories/categoryImage/:id

### Insert One Category
POST http://localhost:9000/v1/categories/insertOne

### Update one Category following the id
PATCH http://localhost:9000/v1/categories/updateOne/:id

### Delete one category with the id
DELETE http://localhost:9000/v1/categories/deleteOne/:id
 
###########################################################################
###SUPPLIERS
GET http://localhost:9000/v1/suppliers

###Update the image of one category
POST http://localhost:9000/v1/suppliers/categoryImage/:id

### Insert One Category
POST http://localhost:9000/v1/suppliers/insertOne

### Update one Category following the id
PATCH http://localhost:9000/v1/suppliers/updateOne/:id

### Delete one category with the id
DELETE http://localhost:9000/v1/categories/deleteOne/:id
 

